export const QUERY_KEYS = {
  GEt_ORDERS_STATISTICS: 'GET_ORDERS_STATISTICS',
  GET_USER_COUNT_BY_TENANT: 'GET_USER_COUNT_BY_TENANT',
  GET_TOTAL_REMAINING_BALANCE: 'GET_TOTAL_REMAINING_BALANCE',
  GET_PRODUCTS_COUNT_BY_TENANT: 'GET_PRODUCTS_COUNT_BY_TENANT',
  GET_LAST_FIVE_ORDERS: 'GET_LAST_FIVE_ORDERS'
};
